#!/bin/bash
# Generate silent 5-second audio fixture files with known metadata.
# Requires ffmpeg.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"

METADATA=(
  -metadata title="Test Track"
  -metadata artist="Test Artist"
  -metadata album_artist="Test Album Artist"
  -metadata album="Test Album"
  -metadata genre="Test Genre"
  -metadata year="2024"
  -metadata track="1/10"
  -metadata disc="1/2"
  -metadata comment="Generated by waveshell test suite"
  -metadata publisher="Test Label"
  -metadata grouping="Test Grouping"
  -metadata replaygain_track_gain="-7.23 dB"
  -metadata replaygain_track_peak="0.876543"
  -metadata replaygain_album_gain="-6.15 dB"
  -metadata replaygain_album_peak="0.912345"
)

echo "Generating FLAC fixture..."
ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 5 \
  "${METADATA[@]}" \
  -metadata:s:a:0 bits_per_sample=24 \
  "$DIR/flac/sample.flac"

echo "Generating MP3 fixture..."
ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 5 \
  -write_id3v2 1 -id3v2_version 4 \
  "${METADATA[@]}" \
  "$DIR/mp3/sample.mp3"

echo "Generating ALAC/M4A fixture..."
ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 5 \
  -acodec alac \
  -metadata title="Test Track" \
  -metadata artist="Test Artist" \
  -metadata album_artist="Test Album Artist" \
  -metadata album="Test Album" \
  -metadata genre="Test Genre" \
  -metadata date="2024" \
  -metadata track="1/10" \
  -metadata disc="1/2" \
  -metadata comment="Generated by waveshell test suite" \
  -metadata label="Test Label" \
  -metadata grouping="Test Grouping" \
  "$DIR/m4a/sample.m4a"

echo "Generating AIFF fixture..."
ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 5 \
  -write_id3v2 1 -id3v2_version 4 \
  "${METADATA[@]}" \
  "$DIR/aiff/sample.aiff"

echo "Generating WAV fixture..."
ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 5 \
  "${METADATA[@]}" \
  "$DIR/wav/sample.wav"

echo "Generating OGG fixture..."
ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 5 \
  -acodec libvorbis \
  -metadata title="Test Track" \
  -metadata artist="Test Artist" \
  -metadata album_artist="Test Album Artist" \
  -metadata album="Test Album" \
  -metadata genre="Test Genre" \
  -metadata date="2024" \
  -metadata track="1/10" \
  -metadata disc="1/2" \
  -metadata comment="Generated by waveshell test suite" \
  -metadata label="Test Label" \
  -metadata grouping="Test Grouping" \
  -metadata REPLAYGAIN_TRACK_GAIN="-7.23 dB" \
  "$DIR/ogg/sample.ogg"

echo "All fixtures generated successfully."
